language: php
php:
  - 5.6
  - 7.0
matrix:
  allow_failures:
    - php: 7.0
env:
  global:
    - APP_ENV=test
    - LOG_SETTING=single
services:
  - postgresql
cache:
  directories:
  - vendor
install:
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - travis_retry composer self-update && travis_retry composer install --no-interaction
script:
  - vendor/bin/phpunit --testsuite "Application Test Suite"
